# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Down' do
pod 'AFNetworking', '2.5.0'
pod 'AFOAuth2Manager'
pod 'Masonry', '0.5.3'
pod 'Parse'
pod 'Facebook-iOS-SDK'
end

